// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolCaseStudy.Data;

#nullable disable

namespace SchoolCaseStudy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927113634_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolCaseStudy.Models.ClassRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ClassRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            GradeLevel = 1,
                            Name = "Class 1A"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 30,
                            GradeLevel = 2,
                            Name = "Class 2A"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 35,
                            GradeLevel = 3,
                            Name = "Class 3A"
                        });
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mathematics Department",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Science Department",
                            Name = "Science"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Languages Department",
                            Name = "Languages"
                        });
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StudentId", "SubjectId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 85m,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 90m,
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 95m,
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 88m,
                            StudentId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 5,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 78m,
                            StudentId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 6,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 92m,
                            StudentId = 4,
                            SubjectId = 3
                        });
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassRoomId = 1,
                            DateOfBirth = new DateTime(2015, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef.ahmed@student.com",
                            FirstName = "Youssef",
                            LastName = "Ahmed",
                            PhoneNumber = "01012345678"
                        },
                        new
                        {
                            Id = 2,
                            ClassRoomId = 1,
                            DateOfBirth = new DateTime(2015, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariam.hassan@student.com",
                            FirstName = "Mariam",
                            LastName = "Hassan",
                            PhoneNumber = "01123456789"
                        },
                        new
                        {
                            Id = 3,
                            ClassRoomId = 2,
                            DateOfBirth = new DateTime(2014, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adam.mohamed@student.com",
                            FirstName = "Adam",
                            LastName = "Mohamed",
                            PhoneNumber = "01234567890"
                        },
                        new
                        {
                            Id = 4,
                            ClassRoomId = 2,
                            DateOfBirth = new DateTime(2014, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laila.ali@student.com",
                            FirstName = "Laila",
                            LastName = "Ali",
                            PhoneNumber = "01098765432"
                        });
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxGrade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Basic Mathematics",
                            MaxGrade = 100,
                            Name = "Mathematics",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "General Science",
                            MaxGrade = 100,
                            Name = "Science",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "English Language",
                            MaxGrade = 100,
                            Name = "English",
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "ahmed.hassan@school.com",
                            FirstName = "Ahmed",
                            LastName = "Hassan",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "sara.ali@school.com",
                            FirstName = "Sara",
                            LastName = "Ali",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "omar.mohamed@school.com",
                            FirstName = "Omar",
                            LastName = "Mohamed",
                            Salary = 0m
                        });
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Enrollment", b =>
                {
                    b.HasOne("SchoolCaseStudy.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolCaseStudy.Models.Subject", "Subject")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Student", b =>
                {
                    b.HasOne("SchoolCaseStudy.Models.ClassRoom", "ClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassRoom");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Subject", b =>
                {
                    b.HasOne("SchoolCaseStudy.Models.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Teacher", b =>
                {
                    b.HasOne("SchoolCaseStudy.Models.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Department", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Subject", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Teacher", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
