// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolCaseStudy.Data;

#nullable disable

namespace SchoolCaseStudy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolCaseStudy.Models.ClassRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ClassRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            GradeLevel = 10,
                            Name = "Class A"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 25,
                            GradeLevel = 11,
                            Name = "Class B"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            GradeLevel = 12,
                            Name = "Class C"
                        });
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Department of Computer Science",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Department of Information Technology",
                            Name = "Information Technology"
                        });
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StudentId", "SubjectId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 90m,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 85m,
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 95m,
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 88m,
                            StudentId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 5,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 78m,
                            StudentId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 6,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 82m,
                            StudentId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 7,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 91m,
                            StudentId = 4,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 8,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 87m,
                            StudentId = 5,
                            SubjectId = 2
                        });
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassRoomId = 1,
                            DateOfBirth = new DateTime(2009, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali.mohamed@student.com",
                            FirstName = "Ali",
                            LastName = "Mohamed",
                            PhoneNumber = "01011111111"
                        },
                        new
                        {
                            Id = 2,
                            ClassRoomId = 1,
                            DateOfBirth = new DateTime(2009, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.ahmed@student.com",
                            FirstName = "Sara",
                            LastName = "Ahmed",
                            PhoneNumber = "01122222222"
                        },
                        new
                        {
                            Id = 3,
                            ClassRoomId = 2,
                            DateOfBirth = new DateTime(2008, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef.mahmoud@student.com",
                            FirstName = "Youssef",
                            LastName = "Mahmoud",
                            PhoneNumber = "01233333333"
                        },
                        new
                        {
                            Id = 4,
                            ClassRoomId = 2,
                            DateOfBirth = new DateTime(2008, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nour.khaled@student.com",
                            FirstName = "Nour",
                            LastName = "Khaled",
                            PhoneNumber = "01044444444"
                        },
                        new
                        {
                            Id = 5,
                            ClassRoomId = 3,
                            DateOfBirth = new DateTime(2007, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariam.tarek@student.com",
                            FirstName = "Mariam",
                            LastName = "Tarek",
                            PhoneNumber = "01155555555"
                        });
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxGrade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Introduction to C# programming",
                            MaxGrade = 100,
                            Name = "C# Programming",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Database concepts and SQL",
                            MaxGrade = 100,
                            Name = "Database",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "HTML, CSS and web development",
                            MaxGrade = 100,
                            Name = "Web Development",
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "ahmed.hassan@school.com",
                            FirstName = "Ahmed",
                            LastName = "Hassan",
                            PhoneNumber = "01012345678",
                            Salary = 15000m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Email = "mona.ali@school.com",
                            FirstName = "Mona",
                            LastName = "Ali",
                            PhoneNumber = "01112345678",
                            Salary = 14000m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Email = "omar.ibrahim@school.com",
                            FirstName = "Omar",
                            LastName = "Ibrahim",
                            PhoneNumber = "01212345678",
                            Salary = 13000m
                        });
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Enrollment", b =>
                {
                    b.HasOne("SchoolCaseStudy.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolCaseStudy.Models.Subject", "Subject")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Student", b =>
                {
                    b.HasOne("SchoolCaseStudy.Models.ClassRoom", "ClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassRoom");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Subject", b =>
                {
                    b.HasOne("SchoolCaseStudy.Models.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Teacher", b =>
                {
                    b.HasOne("SchoolCaseStudy.Models.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Department", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Subject", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SchoolCaseStudy.Models.Teacher", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
